services:
  identity-db:
    image: mysql
    environment:
      MYSQL_DATABASE: identity-db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
  invalidated-token-db:
    image: redis:alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
  redis-insight:
    image: redis/redisinsight
    restart: unless-stopped
    ports:
      - "5540:5540"
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '15672:15672'
      - '5672:5672'
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

volumes:
  rabbitmq-data: