services:
  identity-db:
    image: postgresql:alpine
    environment:
      POSTGRES_DB: identity
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - identity-db-data:/var/lib/postgresql/data