services:
  identity-db:
    image: mysql
    environment:
      MYSQL_DATABASE: identity-db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
  invalidated-token-db:
    image: redis:alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
  redis-insight:
    image: redis/redisinsight
    restart: unless-stopped
    ports:
      - "5540:5540"
