server:
  port: 8080
  servlet:
    context-path: /identity

logging:
  level:
    org.springframework.security.web: DEBUG

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/identity_service"
    username: "root"
    password: "12022004"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
    signerKey: "x1GTfAdnglz/9+9bO9Ya615tMoqNFsdQSUQXolWa5CW3jHaFLQIWoguaoD+GlhPp"
    refreshSignerKey: "7+78pvfH7Pp4WK8py2tecwSfH+Cvt56WKuWNEDOmqsEaiDwjWh2wBI56+gTMMy9S"
    valid-duration: 3600 # in second
    refreshable-duration: 360000 # in second