server:
  port: 8080
  servlet:
    context-path: /identity

logging:
  level:
    org.springframework.security.web: DEBUG

spring:
  application:
    name: identity-service
  datasource:
    url: "jdbc:mysql://localhost:3306/identity-db"
    username: "root"
    password: "root"
    driver-class-name: "com.mysql.cj.jdbc.Driver"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

jwt:
    signer-key: "x1GTfAdnglz/9+9bO9Ya615tMoqNFsdQSUQXolWa5CW3jHaFLQIWoguaoD+GlhPp"
    refresh-signer-key: "7+78pvfH7Pp4WK8py2tecwSfH+Cvt56WKuWNEDOmqsEaiDwjWh2wBI56+gTMMy9S"
    valid-duration: 3600 # in second
    refreshable-duration: 360000 # in second
    revoked-token-prefix: 'revoked_token:'

redis:
  host: "127.0.0.1"
  port: "6379"

app:
  security:
    default-role: USER

service:
  domain: identity
  name: identity-service
  event:
    created: created
    updated: updated
    deleted: deleted

eureka:
  client:
    eureka-server-port: 8761