server:
  port: 8080
  servlet:
    context-path: /identity

logging:
  level:
    org.springframework.security.web: DEBUG

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/identity-service"
    username: "root"
    password: "12022004"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
